on:
  push:
  pull_request:
    branches:
      - devel

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container: ghcr.io/alanocallaghan/scater:latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          dependencies <- remotes::local_package_deps(dependencies = TRUE)
          leftovers <- setdiff(dependencies, installed.packages())
          BiocManager::install(leftovers, ask=FALSE, Ncpu=2L)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error", check_dir = "check")
        shell: Rscript {0}

      # - name: BiocCheck
      #   uses: insightsengineering/bioc-check-action@v1
